---
- name: installing pip, ansible, ansible-lint, ansible-vault
  pip:
    name: ['pip', 'ansible', 'ansible-lint', 'ansible-vault']
    state: latest
  become: yes

- name: create group for ansiblemaster
  group:
    name: "{{ ansible_user_id }}"
    gid: "{{ groupVarAnsibleGid }}"
    state: present
  become: yes

- name: create user for ansible host
  user:
    name: "{{ ansible_user_id }}"
    comment: "{{ ansible_user_id }}"
    uid: "{{ groupVarAnsibleUid }}"
    group: "{{ groupVarAnsibleGid }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: yes

- name: generate logrotate for ansible
  template:
    src: ansible_logrotate.j2
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644
  become: yes

- name: create Ansible Vault File if not existent
  copy:
    dest: "{{ lookup('env','HOME') }}/.ansible/.vault_pass.txt"
    force: no
    content: |
        dummy

- name: generate ansible.cfg
  template:
    src: ansible.j2.cfg
    dest: "{{ lookup('env','HOME') }}/.ansible.cfg"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600

- name: creating sudo privilege for current user
  template:
    src: user.j2.sudo
    dest: "/etc/sudoers.d/{{ ansible_user_id }}"
    owner: root
    group: root
    mode: 0600
  become: yes

- name: creating folder for ansible
  file:
    path: "/home/{{ ansible_user_id }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0700
  with_items:
    - var
    - var/log
    - .ansible
    - .ansible/tmp
...
