---
all:
  children:

    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3

    kvm:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        docker_service_dir: /root/docker
      children:

        k8s-master:
          hosts:
            {{ ip_master }}:

        k8s-worker:
          hosts:
            {{ ip_worker1 }}:
            {{ ip_worker2 }}:     
